# Intro to Numpy 

What is Numpy and why do we use it? 

It's an awesome python package that adds support for large, multi-dimensional arrays. Really good for vector operations, matrix operations because its super parallelized so its super fast! 


Why not Python arrays? 

Python arrays has certain limitations: they don’t support “vectorized” operations like elementwise addition and multiplication, and the fact that they can contain objects of differing types mean that Python must store type information for every element, and must execute type dispatching code when operating on each element. This also means that very few list operations can be carried out by efficient C loops – each iteration would require type checks and other Python API bookkeeping.



### Importing numpy
Functions for numerical computiing are provided by a separate module called `numpy` which we must import.

By convention, we import numpy using the alias `np`.

Once we have done this we can prefix the functions in the numpy library using the prefix `np`.

In [1]:
# This is the de facto way to import NumPy. You probably don't want to write numpy.whatever every time
import numpy as np

### Numpy Arrays
NumPy arrays are the workhorse of the library. A NumPy array is essentially a bunch of data coupled with some metadata:

type: the type of objects in the array. This will typically be floating-point numbers for our purposes, but other types can be stored. The type of an array can be accessed via the `dtype` attribute.

shape: the dimensions of the array. This is given as a tuple, where element $i$ of the tuple tells you how the "length" of the array in the $i$th dimension. For example, a 10-dimensional vector would have shape (10,), a 32-by-100 matrix would have shape (32,100), etc. The shape of an array can be accessed via the `shape` attribute.

Let's see some examples! There are number of ways to construct arrays. One is to pass in a Python sequence (such as list or tuple) to the `np.array` function:

In [2]:
np.array([1, 2.3, -6])

array([ 1. ,  2.3, -6. ])

We can also easily create ordered numerical lists!

In [3]:
# Remember we zero index so you will actually get 0 to 6!
print(np.arange(7))
# Remember the list wont include 9
print(np.arange(3, 9))

[0 1 2 3 4 5 6]
[3 4 5 6 7 8]


We can also customize these list with a third paramter that specifices step size

In [4]:
np.arange(0.0, 100.0, 10.0)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

To create a multi-dimensional array, we'll need to nest the sequences:

In [5]:
np.array([[1, 2.3, -6], [7, 8, 9]])

array([[ 1. ,  2.3, -6. ],
       [ 7. ,  8. ,  9. ]])

Neat! 

There are also many convenience functions for constructing special arrays. Here are some that might be useful: 

In [6]:
# The identity matrix of given size
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [7]:
# A matrix with the given vector on the diagonal
np.diag([1.1,2.2,3.3])

array([[1.1, 0. , 0. ],
       [0. , 2.2, 0. ],
       [0. , 0. , 3.3]])

In [8]:
#An array of all zeros or ones with the given shape
np.zeros((8,4)), np.ones(3)

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([1., 1., 1.]))

In [9]:
# An array with a given shape full of a specified value
np.full((3,4), 2.1)

array([[2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1]])

In [10]:
# A random (standard normal distribution) array with the given shape
np.random.randn(5,6)

array([[ 0.81341685,  1.17550981, -0.80201808,  1.19932684,  0.82435878,
        -0.63872568],
       [-1.86867541, -0.40710058,  0.79487815,  0.73635911,  1.09159444,
        -0.62618679],
       [ 0.03144851,  0.53312724, -0.04560824,  0.36029437, -2.09935847,
        -0.41065755],
       [-0.74209105, -0.57744702, -0.69453664,  0.71901043,  0.19989858,
         0.21656361],
       [ 0.22813712,  0.57435817, -0.73971765, -0.06182445,  0.09108558,
         0.39181337]])

Okay your turn! In the cell belows try and create:


<b>A diagonal matrix with values from 1-20 (try and create this and only type two numbers!)</b>

In [11]:
#Your answer here

Okay now let's suppose we have some data in an array so we can start doing stuff with it.


In [12]:
A = np.random.randn(10,5); x = np.random.randn(5)
A

array([[-0.2098687 , -0.84485124,  1.46556593, -0.30415268, -1.13073263],
       [-0.2095567 ,  0.49496856,  0.1363459 , -1.66477115,  0.91657093],
       [ 1.46417699, -0.4543764 , -1.11830989,  0.89583874,  0.0828412 ],
       [-0.17005318,  0.4028911 ,  1.31917859,  0.62224436, -0.05148068],
       [ 0.58956457,  0.19070868,  1.54516618, -0.04239541, -0.57745488],
       [-2.2203846 ,  0.10684115, -0.06861202,  0.31283397, -1.01210394],
       [ 0.43968543, -2.27040548,  0.70619208, -0.38093667,  0.50733608],
       [-1.25683245,  1.41380855, -1.61115361, -1.68617828, -0.08027384],
       [ 0.54875249, -0.44147648, -0.18756662,  0.10488807,  0.30033466],
       [ 0.53680645, -0.3781728 ,  0.7329108 ,  0.61888022,  1.00343579]])

One useful thing that NumPy lets us do efficiently is apply the same function to every element in an array. You'll often need to e.g. exponentiate a bunch of values, but if you use a list comprehension or map with the builtin Python math functions it may be really slow. Instead just write

In [13]:
# log, sin, cos, etc. work similarly
np.exp(A)

array([[0.81069068, 0.42962126, 4.32999301, 0.73774822, 0.32279668],
       [0.81094366, 1.64044666, 1.14607826, 0.18923396, 2.50070061],
       [4.3239831 , 0.63484373, 0.32683171, 2.44938933, 1.08636928],
       [0.84361996, 1.49614396, 3.74034775, 1.86310483, 0.949822  ],
       [1.80320308, 1.21010687, 4.68875076, 0.9584907 , 0.56132519],
       [0.10856735, 1.11275748, 0.93368886, 1.3672945 , 0.36345349],
       [1.55221887, 0.1032703 , 2.02626072, 0.68322116, 1.66086089],
       [0.28455394, 4.11158479, 0.19965716, 0.18522605, 0.9228636 ],
       [1.73109212, 0.64308622, 0.82897389, 1.11058629, 1.35031063],
       [1.71053544, 0.6851121 , 2.08112955, 1.85684761, 2.72763734]])

We can take the sum/mean/standard deviation/etc. of all the elements in an array:

In [14]:
np.sum(x), np.mean(x), np.std(x)

(1.611628052634808, 0.32232561052696157, 0.5992656986306856)

You can also specify an axis over which to compute the sum if you want a vector of row/column sums (again, sum here can be replaced with mean or other operations):

In [15]:
# Create an array with numbers in the range 0,...,3 (similar to the normal Python range function,
# but it returns a NumPy array) and then reshape it to a 2x2 matrix
B = np.arange(4).reshape((2,2))

# Original matrix, column sum, row sum
B, np.sum(B, axis=0), np.sum(B, axis=1)

(array([[0, 1],
        [2, 3]]),
 array([2, 4]),
 array([1, 5]))

### Linear Algebra
By now we have a pretty good idea of how data is stored and accessed within NumPy arrays. But we typically want to do something more "interesting", which for our ML purposes usually means linear algebra operations. Fortunately, numpy has good support for such routines. Let's see some examples!

In [16]:
# Matrix-vector product. The dimensions have to match, of course
A.dot(x)
# Note that in Python3 there is also a slick notation A @ x which does the same thing

array([-1.3010873 , -1.0105243 ,  2.61021225, -0.3270839 , -0.51154004,
       -2.57682068,  1.45281788, -2.68813371,  1.08490285,  1.69830845])

In [17]:
# Transpose a matrix
A.T

array([[-0.2098687 , -0.2095567 ,  1.46417699, -0.17005318,  0.58956457,
        -2.2203846 ,  0.43968543, -1.25683245,  0.54875249,  0.53680645],
       [-0.84485124,  0.49496856, -0.4543764 ,  0.4028911 ,  0.19070868,
         0.10684115, -2.27040548,  1.41380855, -0.44147648, -0.3781728 ],
       [ 1.46556593,  0.1363459 , -1.11830989,  1.31917859,  1.54516618,
        -0.06861202,  0.70619208, -1.61115361, -0.18756662,  0.7329108 ],
       [-0.30415268, -1.66477115,  0.89583874,  0.62224436, -0.04239541,
         0.31283397, -0.38093667, -1.68617828,  0.10488807,  0.61888022],
       [-1.13073263,  0.91657093,  0.0828412 , -0.05148068, -0.57745488,
        -1.01210394,  0.50733608, -0.08027384,  0.30033466,  1.00343579]])

Now that you're familiar with numpy feel free to check out the documentation and see what else you can do! Documentation can be found here: https://docs.scipy.org/doc/

## Exercises 
Lets try out all the new numpy stuff we just learned! Even if you have experience in numpy we suggest trying these out. 

<b>1) Create a vector of size 10 containing zeros </b>

In [18]:
## FILL IN YOUR ANSWER HERE ##


<b>2) Now change the fith value to be 5 </b>

In [19]:
## FILL IN YOUR ANSWER HERE ##


<b>3) Create a vector with values ranging from 10 to 49</b>

In [20]:
## FILL IN YOUR ANSWER HERE ##


<b>4) Reverse the previous vector (first element becomes last)</b>

In [21]:
## FILL IN YOUR ANSWER HERE ##


<b>5) Create a 3x3 matrix with values ranging from 0 to 8. Create a 1D array first and then resshape it. </b<

In [22]:
## FILL IN YOUR ANSWER HERE ##


<b>6) Create a 3x3x3 array with random values</b>

In [23]:
## FILL IN YOUR ANSWER HERE ##

<b>7) Create a random array and find the sum, mean, and standard deviation</b>

In [24]:
## FILL IN YOUR ANSWER HERE ##